### ISSUE TITLE
[xstate/inspect]-Inspector breaks when window width is less than 640px

### ISSUE THREAD

**Issue by computnik** [davidkpiano/xstate#1431]
Firstly, I would like to add that the inspector looks really promising, and while I was playing around, I saw this bug. 
**Description**

The inspector breaks when window.innerWidth < 640px, and shows "Unexpected error occured"
**Expected Result**

Resize shouldn't break UI
**Actual Result**

It says "Unexpected error occured"
(will 
**Reproduction**

1. Open default Xstate inspector CodeSanbox example
1. Open Inspector
1. Resize the window to less than 640px, to see/reproduce the error

**Additional context**

Please see the video below to see issue reproduction
![bug-report](https://user-images.githubusercontent.com/7376824/92023251-245ba400-ed7a-11ea-9b76-cb81d0a5e817.gif)

**Comment by hemanth** [comment]
This would be an issue on [xstate-viz](https://github.com/statecharts/xstate-viz).

**Comment by computnik** [comment]
> This would be an issue on [xstate-viz](https://github.com/statecharts/xstate-viz)?
> 
> Getting a 404 on [xstate-inspect#readme](https://github.com/davidkpiano/xstate/tree/master/packages/xstate-inspect#readme).

@hemanth I think its in `viz` branch https://github.com/davidkpiano/xstate/tree/viz/packages/xstate-inspect

**Comment by davidkpiano** [comment]
> Firstly, I would like to mention that you folks are doing some great work 👍, and inspector looks really promising.

Thank you!

I could not reproduce this issue. Can you please create a CodeSandbox?

**Comment by computnik** [comment]
@davidkpiano i can see the issue on the default codesandbox https://codesandbox.io/s/xstate-viz-template-f3dtr 
Now i see its turning to a black blank screen instead of that error when width <= 640px

**Comment by johtso** [comment]
Had a poke around and this is the offending CSS:

```css
@media(max-width:40rem) {
 [data-xviz=inspector]>[data-xviz=service] {
  display:block
 }
 [data-xviz=inspector]>[data-xviz=service][data-xviz-view=graph]>:not([data-xviz=machine]),
 [data-xviz=inspector]>[data-xviz=service][data-xviz-view=state]>:not([data-xviz=state]) {
  display:none
 }
}
```
