### ISSUE TITLE
Support delayed events

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#36]
Hi. One of the things I like about statecharts is to deal with delaying events and so on, introducing small wait states that process events differently.

Since xstate is a pure functional thing it doesn't make sense to support delayed events per se, but it would be mighty useful if it were possible to

1. annotate a state with a delayed event
2. show (with an example) how one might code it up (using setTimeout)

One thing is that one would have to know if an event actually exited a state, since exiting a state should cancel the associated timer.

I suggest something a lot simpler than scxml (which doesn't have this built in) (yaml format)

```yaml
states:
  searching:
    on:
      results: displaying_results
    onEntry: startHttpRequest
    onExit: cancelHttpRequest
    states:
      silent:
        after: 2s warning
      warning:
        onEntry: showWarning
```

or something like that. It's important that the timeout doesn't need a name, just a target.

As a user of this I would have to know that a transition _to_ searching state should start a timer, so I can act accordingly, but I also then need to know when I handle an event if I actually exited the searching state at all. Today this might be visible in the returned state's "history", but I would have to inspect the machine myself to know if the new state / historical state have a common ancestor.

E.g. in the state machine above, if I'm in the "searching" "silent" state then an event might _exit_ silent, and I would have to know that this happened, and I think it's hard to infer from the current response

**Comment by davidkpiano** [comment]
Currently, if you have something that understands some `timer_*` action, the above can be translated to: (contrived example)

```yaml
# ...
states:
  silent:
    onEntry: timer_2s_from_silent
    on:
      timer_2s_from_silent_elapsed: warning
      foo: somethingElse
  warning:
    onEntry: showWarning
  somethingElse:
    # ...
```

That way, if you transition to `silent`, the `timer_2s_from_silent` action will set a timer that fires `timer_2s_from_silent_elapsed`. If still on the `silent` state, it will transition to `warning`. If not (e.g., `somethingElse`), that state doesn't handle `timer_2s_from_silent_elapsed` anyway, so nothing will happen.

That definitely gets complicated though, especially if you want to be able to cancel the timer or handle multiple timers.

Another idea (which I'm planning on doing) is adding the feature of specifying actions as _objects_ instead of just strings. This can make it possible to easily model `<send>` in SCXML:

```js
{
  silent: {
    onEntry: { type: 'SEND', event: 'TIMER', delay: 2000 }
    // ...
  },
  // ...
}
```

Which of course can be abstracted into a function:

```js
{
  silent: {
    onEntry: send('TIMER', 2000)
  }
}
```

This would fit best into reactive scenarios, and I'm planning on making demos with RxJS to show how this can be achieved.
